version: "3.5"
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/dashboards
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-image-renderer
    ports:
      - 8081

  grafana-reporter:
    image: izakmarais/grafana-reporter
    container_name: grafana-reporter
    restart: unless-stopped
    ports:
      - "8686:8686"
    volumes:
      - ./grafana/grafana-reporter/data/:/tmp/reporter/
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus/
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  aff-01:
    image: harvest:21.05.3
    container_name: harvest_21.05.3_aff-01
    restart: unless-stopped
    ports:
      - "12991:12991"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ' --poller aff-01 --loglevel 2  --promPort 12991  --config /opt/harvest.yml'
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    volumes:
      - harvest:/opt/harvest/
      - ./harvest/harvest.yml:/opt/harvest.yml

  aff-02:
    image: harvest:21.05.3
    container_name: harvest_21.05.3_aff-02
    restart: unless-stopped
    ports:
      - "12992:12992"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ' --poller aff-02 --loglevel 2  --promPort 12992  --config /opt/harvest.yml'
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    volumes:
      - harvest:/opt/harvest/
      - ./harvest/harvest.yml:/opt/harvest.yml

volumes:
  harvest:
  prometheus:
  grafana: